# ===============================
# Application
# ===============================
quarkus.application.name=mail-quarkus-service
quarkus.application.version=1.0.0
# ===============================
# HTTP
# ===============================
quarkus.http.port=8080
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:3000,https://login-chi-dusky.vercel.app,https://hrfrontendv1.netlify.app,https://adminfrontend-bice-eta.vercel.app
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
quarkus.http.cors.headers=*
quarkus.http.cors.access-control-allow-credentials=true
# ===============================
# DATABASE
# ===============================
# quarkus.datasource.db-kind=postgresql
# quarkus.datasource.jdbc.url=jdbc:postgresql://ep-nameless-flower-ahqfkw3x-pooler.c-3.us-east-1.aws.neon.tech/mail-db?sslmode=require
# quarkus.datasource.username=neondb_owner
# quarkus.datasource.password=npg_ODZx4pvMKCU1
# Local
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres?options=-c%20TimeZone=Asia%2FHo_Chi_Minh&stringtype=unspecified
quarkus.datasource.username=postgres
quarkus.datasource.password=12345
#
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
# JDBC Batching cho tốc độ cao
quarkus.hibernate-orm.jdbc.statement-batch-size=20
quarkus.hibernate-orm.jdbc.order-inserts=true
quarkus.hibernate-orm.jdbc.order-updates=true
quarkus.datasource.jdbc.max-size=50
# ===============================
# KAFKA (CHỈ GIỮ 1 CONFIG)
# ===============================
# quarkus.kafka.devservices.enabled=false
# mp.messaging.connector.smallrye-kafka.bootstrap.servers=kafka-2d3930ef-student-337e.g.aivencloud.com:24786
# mp.messaging.connector.smallrye-kafka.security.protocol=SSL
# mp.messaging.connector.smallrye-kafka.ssl.keystore.location=certs/kafka.keystore.p12
# mp.messaging.connector.smallrye-kafka.ssl.keystore.password=changeit
# mp.messaging.connector.smallrye-kafka.ssl.truststore.location=certs/kafka.truststore.jks
# mp.messaging.connector.smallrye-kafka.ssl.truststore.password=changeit
# Local
quarkus.kafka.devservices.enabled=false
kafka.bootstrap.servers=localhost:9092
mp.messaging.connector.smallrye-kafka.bootstrap.servers=localhost:9092
mp.messaging.connector.smallrye-kafka.security.protocol=PLAINTEXT
#
mp.messaging.incoming.mail-requests.value.deserialization-failure-handler=failure-fallback
mp.messaging.incoming.mail-requests.failure-strategy=ignore
# INPUT: mail-requests (Kafka → Consumer)
mp.messaging.incoming.mail-requests.connector=smallrye-kafka
mp.messaging.incoming.mail-requests.topic=mail_requests_1
mp.messaging.incoming.mail-requests.group.id=mail-consumer-group
mp.messaging.incoming.mail-requests.value.deserializer=org.atlas_erp.Config.SafeJsonDeserializer
mp.messaging.incoming.mail-requests.json.value.type=org.atlas_erp.dto.MailEventDTO
# --- OUTPUT & INPUT: internal-jobs ---
mp.messaging.outgoing.internal-jobs-out.connector=smallrye-kafka
mp.messaging.outgoing.internal-jobs-out.topic=internal_jobs
mp.messaging.outgoing.internal-jobs-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer
#
mp.messaging.incoming.internal-jobs-in.connector=smallrye-kafka
mp.messaging.incoming.internal-jobs-in.topic=internal_jobs
mp.messaging.incoming.internal-jobs-in.group.id=mail-worker-group
mp.messaging.incoming.internal-jobs-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.internal-jobs-in.max-concurrency=10
# --- BATCH REQUESTS ---
mp.messaging.outgoing.mail-batch-requests-out.connector=smallrye-kafka
mp.messaging.outgoing.mail-batch-requests-out.topic=user-activity-log-1
#
mp.messaging.incoming.mail-batch-requests-in.connector=smallrye-kafka
mp.messaging.incoming.mail-batch-requests-in.topic=user-activity-log-1
mp.messaging.incoming.mail-batch-requests-in.group.id=mail-batch-worker-group
mp.messaging.incoming.mail-batch-requests-in.value.deserializer.record-type=org.atlas_erp.dto.MailBatchEventDTO
mp.messaging.incoming.mail-batch-requests-in.max-concurrency=10
# ===============================
# MAIL
# ===============================
quarkus.mailer.host=localhost
quarkus.mailer.port=1025
quarkus.mailer.mock=false